### ISSUE TITLE
uploading image error

### ISSUE THREAD

**Issue by telescope2024** [LPengYang/FreeDrag#11]
Hello. I wanted to ask regarding uploading custom images. When I click the small "x" on the top right corner, which then shows "Drop Image Here -or- Click to Upload", and then upload my own image, after some time, it uploads my own image. However, it is either much distorted that differs from the original image although it works well for images from the given .pkl files. For example, although I have used 512x512 (as stated in your github) cat image with cats.pkl, the uploaded image is much changed. So, can I ask whether I am uploading image incorrectly? 

![freedragcat](https://github.com/LPengYang/FreeDrag/assets/152045092/c6179180-3ec6-4493-a7d0-949cb01d8885)
![resized_image](https://github.com/LPengYang/FreeDrag/assets/152045092/938c6455-cf43-4d65-9962-672b8ff10d67)

**Comment by LPengYang** [comment]
Hi, the image inversion of StyleGAN sometimes receives low quality due to the limited generation ability of GAN.
We now add the implementation of diffusion-based FreeDrag, which performs higher inversion quality based on SD 1.5 and thus is suggested in real image editing. We will also update the details about the implementation in few days.

**Comment by LPengYang** [comment]
Hi, the updated paper is now available, which contains more implementation details on both GAN-based models and Diffusion models.
