### ISSUE TITLE
About gradio demo

### ISSUE THREAD

**Issue by ButoneDream** [LPengYang/FreeDrag#14]
2 question
1.upload image slowly
![image](https://github.com/LPengYang/FreeDrag/assets/98502973/46dc0a5d-da74-4416-94ad-15a2478bdf46)
2. When I upload a local image, it becomes blurry and distorted.
![image](https://github.com/LPengYang/FreeDrag/assets/98502973/e30049c3-dbb4-46aa-b43a-62bf8c9a5675)
the original image ：
![image](https://github.com/LPengYang/FreeDrag/assets/98502973/30d15a03-f7cc-4a73-ada3-97dd551b0c69)

How can this be resolved?

**Comment by LPengYang** [comment]
Sorry for being late. This distortion happens because StyleGAN is a uni-modal model, i.e., it can only produce the results within its distribution, human face in this case. For inversion, the image input should be aligned. Also, the diffusion-based freedrag (also be provided) is recommended for real image inversion due to the higher generalizability of the diffusion model.

**Comment by ButoneDream** [comment]
thanks 
however， i could not find how to try Diffusion-based FreeDrag demo ?
could you help me ??

**Comment by LPengYang** [comment]
run the drag_ui.py in the FreeDrag-diffusion-version file
