### ISSUE TITLE
 Diffusion-based FreeDrag？

### ISSUE THREAD

**Issue by JoshonSmith** [LPengYang/FreeDrag#8]
looking forward to Diffusion-based FreeDrag

**Comment by LPengYang** [comment]
Hi, Sorry to be so late due to other task. 
We have added the implementation of Diffusion-based FreeDrag, which supports real image dragging (image inversion) and generated image (SD 1.5) dragging. The diffusion-based FreeDrag is based on DragDiffusion with permission. If you have any problem in implementation, please contact us and we will fix it at once.
