### ISSUE TITLE
change inversion model

### ISSUE THREAD

**Issue by GODGANG4885** [LPengYang/FreeDrag#9]
Gan inversion results are not good.
Is it possible to replace it with the PTI model?
 https://github.com/danielroich/PTI/tree/da94d59d15d94822e95840ab5a0aa9ba1a19c851

**Comment by LPengYang** [comment]
Thanks for your reminder, we will make a try.

**Comment by LPengYang** [comment]
> Gan inversion results are not good. Is it possible to replace it with the PTI model? https://github.com/danielroich/PTI/tree/da94d59d15d94822e95840ab5a0aa9ba1a19c851

Hi, the image inversion of StyleGAN sometimes receives low quality due to the limited generation ability of GAN.
We now add the implementation of diffusion-based FreeDrag, which performs higher inversion quality based on SD 1.5 and thus is suggested in real image editing. We will also update the details about the implementation in few days.
